name:ESP32 ST7796 3.5in 480x320 FT6336
description:Example of using the ST7796 3.5" display (480x320, SPI) on ESP32 with capacitive touch FT6336 (I2C). Demonstrates drawing and touch input with the displayfk library.
exampleFileName:Arduino1x__ESP32__BLACK_ST7796_35-20260225T12470.ewx
