name:S3-Embed 8048S070 800x480 GT911
description:Example of using the embedded display ESP32-8048S070 (800x480) on ESP32-S3 embedded, with capacitive touch GT911 (I2C). Demonstrates drawing and widgets with the displayfk library.
