name:P4-Embed Guition DSI 4in 800x480 GT911
description:Example of using the ST7701 DSI 4" display (800x480) on ESP32-P4 embedded, with capacitive touch GT911 (I2C). Demonstrates drawing and widgets with the displayfk library.
exampleFileName:Arduino1x__P4EMBED__GUITION_DSI_4-20260225T12491.ewx
