name:ESP32-S3 ILI9488 4in 320x480 XPT2046
description:Example of using the ILI9488 4" display (480x320, SPI) on ESP32-S3 with resistive touch XPT2046 (SPI). Demonstrates drawing and touch input with the displayfk library.
