name:ESP32-S3 ILI9488 240x320 XPT2046
description:Example of using the ILI9488 display (240x320, SPI) on ESP32-S3 with resistive touch XPT2046 (SPI). Demonstrates drawing and touch input with the displayfk library.
exampleFileName:Arduino1x__ESP32S3__ILI9488_XPT2046-20260302T12052.ewx
