name:P4-Embed Waveshare DSI 10in 1280x800 GSL3680
description:Example of using the JD9365 DSI 10" display (1280x800) on ESP32-P4 embedded, with capacitive touch GSL3680 (I2C). Demonstrates drawing and widgets with the displayfk library.
