name:S3-Embed Waveshare ST7262 800x480 GT911
description:Example of using the Waveshare ST7262 display (800x480, RGB) on ESP32-S3 embedded, with capacitive touch GT911 (I2C). Demonstrates drawing and widgets with the displayfk library.
exampleFileName:Arduino1x__S3EMBED__WAVESHARE_ST7262-20260225T12390.ewx
