name:S3-Embed 4827S043 480x272 XPT2046
description:Example of using the embedded display ESP32-4827S043 (480x272) on ESP32-S3 embedded, with resistive touch XPT2046 (SPI). Demonstrates drawing and widgets with the displayfk library.
