name:ESP32-Embed ST7796 480x320 XPT2046
description:Example of using the ST7796 display (480x320, embedded) on ESP32 embedded, with resistive touch XPT2046 (SPI). Demonstrates drawing and touch input with the displayfk library.
exampleFileName:Arduino1x__ESP32EMBED__ST7796_YELLOW-20260225T13064.ewx
