name:P4-Embed Guition DSI 7in 1024x600 GT911
description:Example of using the JD9165 DSI 7" display (1024x600) on ESP32-P4 embedded, with capacitive touch GT911 (I2C). Demonstrates drawing and widgets with the displayfk library.
exampleFileName:Arduino1x__P4EMBED__GUITION_DSI_7-20260225T12494.ewx
