name:ESP32 ILI9488 4in 320x480 FT6336
description:Example of using the ILI9488 4" display (320x480, SPI) on ESP32 with capacitive touch FT6336 (I2C). Demonstrates drawing and touch input with the displayfk library.
exampleFileName:Arduino1x__ESP32__ILI9488_4_FT6336-20260225T12172.ewx
