name:ESP32-Embed Guition 2.8in 320x240 CST820
description:Example of using the ST7789 2.8" display (320x240, embedded) on ESP32 embedded, with capacitive touch CST820 (I2C). Demonstrates drawing and touch input with the displayfk library.
exampleFileName:Arduino1x__ESP32EMBED__GUITION_28-20260225T12474.ewx
