name:S3-Embed ST7789 8bit 170x320
description:Example of using the ST7789 display in 8-bit mode (170x320) on ESP32-S3 embedded, no touch. Demonstrates drawing and widgets with the displayfk library.
exampleFileName:Arduino1x__S3EMBED__ST7789_8bit-20260225T12284.ewx
