name:ESP32-S3 ILI9225 176x220
description:Example of using the ILI9225 display (176x220, SPI) on ESP32-S3, no touch. Demonstrates drawing and widgets with the displayfk library.
exampleFileName:Arduino1x__ESP32S3__ILI9225_NO_TOUCH.ewx
